// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var activeLine, addLine, editCell, editor, marginCell;
    editor = $("<table />").appendTo("body");
    activeLine = false;
    editCell = function(line) {
      var cell, input;
      cell = $("<td />").addClass('code').append(input = $("<input />"));
      cell.on('click', function() {
        return cell.focus();
      });
      cell.focus = function() {
        input.focus();
        return activeLine = line;
      };
      input.on('keydown', function(e) {
        if (e.keyCode === 9) {
          return e.preventDefault();
        }
      });
      input.on('keyup', function(e) {
        if (e.keyCode === 9) {
          console.log("tab");
        }
        if (e.keyCode === 38 && line.prior) {
          line.prior.code.focus();
        }
        if (e.keyCode === 40 && line.next) {
          line.next.code.focus();
        }
        if (e.keyCode === 8 && input.val().replace(/\s+/, '').length === 0 && line.prior) {
          line.container.remove();
          line.prior.code.focus();
        }
        if (e.keyCode === 13) {
          return line.next = addLine().code.focus();
        }
      });
      return cell;
    };
    marginCell = function() {
      return $("<td />").addClass("margin").attr({
        width: "100",
        contentEditable: true
      });
    };
    addLine = function() {
      var line;
      line = {
        prior: activeLine,
        next: false
      };
      line.container = $("<tr />").append(line.comment = marginCell(), line.code = editCell(line));
      if (activeLine) {
        activeLine.container.after(line.container);
      } else {
        editor.append(line.container);
      }
      return line;
    };
    return addLine().code.focus();
  });

}).call(this);
